// export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const ADD_SUBCATEGORIES = 'ADD_SUBCATEGORIES';
export const CLICKED_CATEGORY = 'CLICKED_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_CHALLENGES = 'GET_CHALLENGES';
export const CLICKED_SUBCATEGORY = 'CLICKED_SUBCATEGORY';
export const SELECTED_CHALLENGE = 'SELECTED_CHALLENGE';